jpa:
  properties:
    hibernate:
      show-sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: none
spring:
  jpa:
    open-in-view: false
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /api