spring:
  data:
    redis:
      repositories:
        enabled: false


  autoconfigure:
    exclude=org:
      springframework:
        boot:
          autoconfigure:
            data:
              redis:
                RedisAutoConfiguration: