spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/news_comments
    url: jdbc:postgresql://localhost:5432/prod_db
    username: postgres
    password: postgres
  liquibase:
    contexts: prod
cache:
  algorithm: LFU
  capacity: 50

