spring:
  profiles:
    default: dev

#    active: prod

  elasticsearch:
    restclient:
      sniffer:
        interval: 60m
        delay-after-failure: 60m

server:
  port: 8083

micro-search:
  openapi:
    dev-url: http://localhost:8083
    prod-url: micro-search:8083







